security:
    # ...
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        # ...
        main:
            # ...
            provider: app_user_provider
    # ...